chore: repo updates
defenseunicorns/lula-action pull request #9
Opened 2024-07-09 17:25 UTC by CloudBeard

Updated repo to become a lula first class repo.

2024-07-09 17:33 UTC, brandtkeller requested changes
Release please and other configuration for renovate/ pipelines/ templates etc looks good. 

I don't believe we need any golang related content - to include `goreleaser` and I'd also vet how necessary the sbom action tool is.

Are we able to down-select and remove unnecessary content?

2024-07-09 17:59 UTC, CloudBeard commented
The SBOM action is needed for goreleaser. removed goreleaser and all of those dependencies.

2024-07-10 13:39 UTC, brandtkeller requested changes
Updated the repo maintainers to include `lula-dev` such that the codeowners file is now valid. Few mentions of go-releaser to remove and update accordingly otherwise this looks on track.

2024-07-10 13:39 UTC, brandtkeller commented on docs/community-and-contribution/release-process.md
> +This project uses [goreleaser](https://github.com/goreleaser/goreleaser-action) for releasing binaries and [release-please](https://github.com/marketplace/actions/release-please-action) for creating
mention of go-releaser needs removal

2024-07-10 13:39 UTC, brandtkeller commented on docs/community-and-contribution/release-process.md
> +- Confirm that the goreleaser configuration is valid by using the [goreleaser cli](https://goreleaser.com/cmd/goreleaser_check/?h=valid)
mention of go-releaser needs removal

2024-07-10 15:26 UTC, brandtkeller commented on README.md
> +  uses: defenseunicorns/lula-action/setup@v1
can you change the version to main on all of these real quick? Until we sort out which version we are going to use.

2024-07-10 22:53 UTC, brandtkeller approved these changes

2024-07-16 03:45 UTC, merged